#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v4
# autospec commit: f4bef72
#
Name     : libmsgraph
Version  : 0.2.1
Release  : 1
URL      : https://gitlab.gnome.org/GNOME/msgraph/-/archive/0.2.1/msgraph-0.2.1.tar.gz
Source0  : https://gitlab.gnome.org/GNOME/msgraph/-/archive/0.2.1/msgraph-0.2.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: libmsgraph-data = %{version}-%{release}
Requires: libmsgraph-lib = %{version}-%{release}
Requires: libmsgraph-license = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : gi-docgen
BuildRequires : gnome-online-accounts-dev
BuildRequires : json-glib-dev
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(json-glib-1.0)
BuildRequires : pkgconfig(rest-1.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# libmsgraph
libmsgraph is a GLib-based library for accessing online serive APIs using MS Graph protocol.

%package data
Summary: data components for the libmsgraph package.
Group: Data

%description data
data components for the libmsgraph package.


%package dev
Summary: dev components for the libmsgraph package.
Group: Development
Requires: libmsgraph-lib = %{version}-%{release}
Requires: libmsgraph-data = %{version}-%{release}
Provides: libmsgraph-devel = %{version}-%{release}
Requires: libmsgraph = %{version}-%{release}

%description dev
dev components for the libmsgraph package.


%package doc
Summary: doc components for the libmsgraph package.
Group: Documentation

%description doc
doc components for the libmsgraph package.


%package lib
Summary: lib components for the libmsgraph package.
Group: Libraries
Requires: libmsgraph-data = %{version}-%{release}
Requires: libmsgraph-license = %{version}-%{release}

%description lib
lib components for the libmsgraph package.


%package license
Summary: license components for the libmsgraph package.
Group: Default

%description license
license components for the libmsgraph package.


%prep
%setup -q -n msgraph-0.2.1
cd %{_builddir}/msgraph-0.2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1710888398
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain -Dtests=false  builddir
ninja -v -C builddir

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/libmsgraph
cp %{_builddir}/msgraph-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libmsgraph/a8a12e6867d7ee39c21d9b11a984066099b6fb6b || :
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/Msg-0.typelib
/usr/share/gir-1.0/*.gir

%files dev
%defattr(-,root,root,-)
/usr/include/msg/contact/msg-contact-service.h
/usr/include/msg/contact/msg-contact.h
/usr/include/msg/drive/msg-drive-item-file.h
/usr/include/msg/drive/msg-drive-item-folder.h
/usr/include/msg/drive/msg-drive-item.h
/usr/include/msg/drive/msg-drive-service.h
/usr/include/msg/drive/msg-drive.h
/usr/include/msg/message/msg-mail-folder.h
/usr/include/msg/message/msg-message-service.h
/usr/include/msg/message/msg-message.h
/usr/include/msg/msg-authorizer.h
/usr/include/msg/msg-error.h
/usr/include/msg/msg-goa-authorizer.h
/usr/include/msg/msg-input-stream.h
/usr/include/msg/msg-oauth2-authorizer.h
/usr/include/msg/msg-private.h
/usr/include/msg/msg-service.h
/usr/include/msg/msg-version.h
/usr/include/msg/msg.h
/usr/include/msg/user/msg-user-service.h
/usr/include/msg/user/msg-user.h
/usr/lib64/libmsgraph-0.so
/usr/lib64/pkgconfig/msgraph-0.1.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/msgraph-0/RedHatDisplay-Black.woff
/usr/share/doc/msgraph-0/RedHatDisplay-Black.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-BlackItalic.woff
/usr/share/doc/msgraph-0/RedHatDisplay-BlackItalic.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-Bold.woff
/usr/share/doc/msgraph-0/RedHatDisplay-Bold.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-BoldItalic.woff
/usr/share/doc/msgraph-0/RedHatDisplay-BoldItalic.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-Italic.woff
/usr/share/doc/msgraph-0/RedHatDisplay-Italic.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-Medium.woff
/usr/share/doc/msgraph-0/RedHatDisplay-Medium.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-MediumItalic.woff
/usr/share/doc/msgraph-0/RedHatDisplay-MediumItalic.woff2
/usr/share/doc/msgraph-0/RedHatDisplay-Regular.woff
/usr/share/doc/msgraph-0/RedHatDisplay-Regular.woff2
/usr/share/doc/msgraph-0/RedHatText-Bold.woff
/usr/share/doc/msgraph-0/RedHatText-Bold.woff2
/usr/share/doc/msgraph-0/RedHatText-BoldItalic.woff
/usr/share/doc/msgraph-0/RedHatText-BoldItalic.woff2
/usr/share/doc/msgraph-0/RedHatText-Italic.woff
/usr/share/doc/msgraph-0/RedHatText-Italic.woff2
/usr/share/doc/msgraph-0/RedHatText-Medium.woff
/usr/share/doc/msgraph-0/RedHatText-Medium.woff2
/usr/share/doc/msgraph-0/RedHatText-MediumItalic.woff
/usr/share/doc/msgraph-0/RedHatText-MediumItalic.woff2
/usr/share/doc/msgraph-0/RedHatText-Regular.woff
/usr/share/doc/msgraph-0/RedHatText-Regular.woff2
/usr/share/doc/msgraph-0/SourceCodePro-It.ttf.woff
/usr/share/doc/msgraph-0/SourceCodePro-Regular.ttf.woff
/usr/share/doc/msgraph-0/SourceCodePro-Semibold.ttf.woff
/usr/share/doc/msgraph-0/build-howto.html
/usr/share/doc/msgraph-0/class.Contact.html
/usr/share/doc/msgraph-0/class.ContactService.html
/usr/share/doc/msgraph-0/class.Drive.html
/usr/share/doc/msgraph-0/class.DriveItem.html
/usr/share/doc/msgraph-0/class.DriveItemFile.html
/usr/share/doc/msgraph-0/class.DriveItemFolder.html
/usr/share/doc/msgraph-0/class.DriveService.html
/usr/share/doc/msgraph-0/class.GoaAuthorizer.html
/usr/share/doc/msgraph-0/class.InputStream.html
/usr/share/doc/msgraph-0/class.MailFolder.html
/usr/share/doc/msgraph-0/class.Message.html
/usr/share/doc/msgraph-0/class.MessageService.html
/usr/share/doc/msgraph-0/class.OAuth2Authorizer.html
/usr/share/doc/msgraph-0/class.Service.html
/usr/share/doc/msgraph-0/class.User.html
/usr/share/doc/msgraph-0/class.UserService.html
/usr/share/doc/msgraph-0/classes_hierarchy.html
/usr/share/doc/msgraph-0/const.API_ENDPOINT.html
/usr/share/doc/msgraph-0/ctor.Contact.new.html
/usr/share/doc/msgraph-0/ctor.Contact.new_from_json.html
/usr/share/doc/msgraph-0/ctor.ContactService.new.html
/usr/share/doc/msgraph-0/ctor.Drive.new.html
/usr/share/doc/msgraph-0/ctor.Drive.new_from_json.html
/usr/share/doc/msgraph-0/ctor.DriveItem.new_from_json.html
/usr/share/doc/msgraph-0/ctor.DriveItemFile.new.html
/usr/share/doc/msgraph-0/ctor.DriveItemFile.new_from_json.html
/usr/share/doc/msgraph-0/ctor.DriveItemFolder.new.html
/usr/share/doc/msgraph-0/ctor.DriveItemFolder.new_from_json.html
/usr/share/doc/msgraph-0/ctor.DriveService.new.html
/usr/share/doc/msgraph-0/ctor.GoaAuthorizer.new.html
/usr/share/doc/msgraph-0/ctor.InputStream.new.html
/usr/share/doc/msgraph-0/ctor.MailFolder.new.html
/usr/share/doc/msgraph-0/ctor.MailFolder.new_from_json.html
/usr/share/doc/msgraph-0/ctor.Message.new.html
/usr/share/doc/msgraph-0/ctor.Message.new_from_json.html
/usr/share/doc/msgraph-0/ctor.MessageService.new.html
/usr/share/doc/msgraph-0/ctor.OAuth2Authorizer.new.html
/usr/share/doc/msgraph-0/ctor.Service.new.html
/usr/share/doc/msgraph-0/ctor.User.new.html
/usr/share/doc/msgraph-0/ctor.User.new_from_json.html
/usr/share/doc/msgraph-0/ctor.UserService.new.html
/usr/share/doc/msgraph-0/enum.DriveType.html
/usr/share/doc/msgraph-0/enum.LogLevel.html
/usr/share/doc/msgraph-0/enum.MessageMailFolderType.html
/usr/share/doc/msgraph-0/error.Error.html
/usr/share/doc/msgraph-0/fonts.css
/usr/share/doc/msgraph-0/func.OAUTH2_AUTHORIZER.html
/usr/share/doc/msgraph-0/func.OAUTH2_AUTHORIZER_CLASS.html
/usr/share/doc/msgraph-0/func.error_quark.html
/usr/share/doc/msgraph-0/fzy.js
/usr/share/doc/msgraph-0/go-up-symbolic.png
/usr/share/doc/msgraph-0/iface.Authorizer.html
/usr/share/doc/msgraph-0/index.html
/usr/share/doc/msgraph-0/index.json
/usr/share/doc/msgraph-0/main.js
/usr/share/doc/msgraph-0/method.Authorizer.process_request.html
/usr/share/doc/msgraph-0/method.Authorizer.refresh_authorization.html
/usr/share/doc/msgraph-0/method.Contact.get_given_name.html
/usr/share/doc/msgraph-0/method.Contact.get_id.html
/usr/share/doc/msgraph-0/method.Contact.get_name.html
/usr/share/doc/msgraph-0/method.Contact.get_surname.html
/usr/share/doc/msgraph-0/method.Contact.set_given_name.html
/usr/share/doc/msgraph-0/method.Contact.set_surname.html
/usr/share/doc/msgraph-0/method.ContactService.create.html
/usr/share/doc/msgraph-0/method.ContactService.delete.html
/usr/share/doc/msgraph-0/method.ContactService.get_contacts.html
/usr/share/doc/msgraph-0/method.Drive.get_created.html
/usr/share/doc/msgraph-0/method.Drive.get_drive_type.html
/usr/share/doc/msgraph-0/method.Drive.get_id.html
/usr/share/doc/msgraph-0/method.Drive.get_modified.html
/usr/share/doc/msgraph-0/method.Drive.get_name.html
/usr/share/doc/msgraph-0/method.Drive.get_remaining.html
/usr/share/doc/msgraph-0/method.Drive.get_total.html
/usr/share/doc/msgraph-0/method.Drive.get_used.html
/usr/share/doc/msgraph-0/method.DriveItem.get_created.html
/usr/share/doc/msgraph-0/method.DriveItem.get_drive_id.html
/usr/share/doc/msgraph-0/method.DriveItem.get_etag.html
/usr/share/doc/msgraph-0/method.DriveItem.get_id.html
/usr/share/doc/msgraph-0/method.DriveItem.get_modified.html
/usr/share/doc/msgraph-0/method.DriveItem.get_name.html
/usr/share/doc/msgraph-0/method.DriveItem.get_parent_id.html
/usr/share/doc/msgraph-0/method.DriveItem.get_size.html
/usr/share/doc/msgraph-0/method.DriveItem.get_user.html
/usr/share/doc/msgraph-0/method.DriveItem.is_shared.html
/usr/share/doc/msgraph-0/method.DriveItem.set_id.html
/usr/share/doc/msgraph-0/method.DriveItem.set_name.html
/usr/share/doc/msgraph-0/method.DriveItem.set_parent_id.html
/usr/share/doc/msgraph-0/method.DriveItemFile.get_mime_type.html
/usr/share/doc/msgraph-0/method.DriveItemFile.get_thumbnail_uri.html
/usr/share/doc/msgraph-0/method.DriveService.add_item_to_folder.html
/usr/share/doc/msgraph-0/method.DriveService.create_folder.html
/usr/share/doc/msgraph-0/method.DriveService.delete.html
/usr/share/doc/msgraph-0/method.DriveService.download_item.html
/usr/share/doc/msgraph-0/method.DriveService.download_url.html
/usr/share/doc/msgraph-0/method.DriveService.get_drives.html
/usr/share/doc/msgraph-0/method.DriveService.get_root.html
/usr/share/doc/msgraph-0/method.DriveService.get_shared_with_me.html
/usr/share/doc/msgraph-0/method.DriveService.list_children.html
/usr/share/doc/msgraph-0/method.DriveService.rename.html
/usr/share/doc/msgraph-0/method.DriveService.update.html
/usr/share/doc/msgraph-0/method.DriveService.update_finish.html
/usr/share/doc/msgraph-0/method.GoaAuthorizer.get_goa_object.html
/usr/share/doc/msgraph-0/method.MailFolder.get_display_name.html
/usr/share/doc/msgraph-0/method.MailFolder.get_total_item_count.html
/usr/share/doc/msgraph-0/method.MailFolder.get_unread_item_count.html
/usr/share/doc/msgraph-0/method.Message.get_body_preview.html
/usr/share/doc/msgraph-0/method.Message.get_id.html
/usr/share/doc/msgraph-0/method.Message.get_subject.html
/usr/share/doc/msgraph-0/method.Message.set_body.html
/usr/share/doc/msgraph-0/method.Message.set_subject.html
/usr/share/doc/msgraph-0/method.MessageService.create_draft.html
/usr/share/doc/msgraph-0/method.MessageService.delete.html
/usr/share/doc/msgraph-0/method.MessageService.get_mail_folder.html
/usr/share/doc/msgraph-0/method.MessageService.get_mail_folders.html
/usr/share/doc/msgraph-0/method.MessageService.get_messages.html
/usr/share/doc/msgraph-0/method.OAuth2Authorizer.build_authentication_uri.html
/usr/share/doc/msgraph-0/method.OAuth2Authorizer.request_authorization.html
/usr/share/doc/msgraph-0/method.Service.build_message.html
/usr/share/doc/msgraph-0/method.Service.get_authorizer.html
/usr/share/doc/msgraph-0/method.Service.get_session.html
/usr/share/doc/msgraph-0/method.Service.refresh_authorization.html
/usr/share/doc/msgraph-0/method.Service.send.html
/usr/share/doc/msgraph-0/method.Service.send_and_read.html
/usr/share/doc/msgraph-0/method.User.get_mail.html
/usr/share/doc/msgraph-0/method.UserService.get_user.html
/usr/share/doc/msgraph-0/msgraph-0.devhelp2
/usr/share/doc/msgraph-0/property.GoaAuthorizer.goa-object.html
/usr/share/doc/msgraph-0/property.OAuth2Authorizer.client-id.html
/usr/share/doc/msgraph-0/property.OAuth2Authorizer.redirect-uri.html
/usr/share/doc/msgraph-0/property.OAuth2Authorizer.refresh-token.html
/usr/share/doc/msgraph-0/property.Service.authorizer.html
/usr/share/doc/msgraph-0/search.js
/usr/share/doc/msgraph-0/solarized-dark.css
/usr/share/doc/msgraph-0/solarized-light.css
/usr/share/doc/msgraph-0/struct._DriveItemFileClass.html
/usr/share/doc/msgraph-0/struct._DriveItemFolderClass.html
/usr/share/doc/msgraph-0/style.css
/usr/share/doc/msgraph-0/type_func.InputStream.get_message.html
/usr/share/doc/msgraph-0/type_func.InputStream.send_async.html
/usr/share/doc/msgraph-0/type_func.InputStream.send_finish.html
/usr/share/doc/msgraph-0/type_func.OAuth2Authorizer.test_load_credentials.html
/usr/share/doc/msgraph-0/type_func.OAuth2Authorizer.test_save_credentials.html
/usr/share/doc/msgraph-0/type_func.Service.accept_certificate_cb.html
/usr/share/doc/msgraph-0/type_func.Service.get_https_port.html
/usr/share/doc/msgraph-0/type_func.Service.parse_response.html
/usr/share/doc/msgraph-0/vfunc.Authorizer.process_request.html
/usr/share/doc/msgraph-0/vfunc.Authorizer.refresh_authorization.html

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmsgraph-0.so.0.2.1
/usr/lib64/libmsgraph-0.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libmsgraph/a8a12e6867d7ee39c21d9b11a984066099b6fb6b
